### ISSUE TITLE
Options documentation improvements

### ISSUE THREAD

**Issue by abrevers-nttdata** [ascii42/check_vmware_horizon#1]
The documentation format about options is inconsistent:

` -eCS---enable-connectionserver`
  should be
` -eCS, --enable-connectionserver`

` -eGW--enable-gateway`
should be
` -eGW, --enable-gateway`

` -eVC--enable-vcenter`
should be
` -eVC, --enable-vcenter`

` -eDB--enable-db`
should be
` -eDB, --enable-db`

` -eAD--enable-ad`
should be
` -eAD, --enable-ad`

` -eRDS--enable-rds`
should be
` -eRDS, --enable-rds`

` -eFA--enable-farms`
should be
` -eFA, --enable-farms`

` -eSA--enable-saml`
should be
` -eSA, --enable-saml`

` -eTS--enable-truesso`
should be
` -eTS, --enable-truesso`

` -ePO--enable-pod`
should be
` -ePO, --enable-pod`

` -A|--enable-all`
should be
` -A, --enable-all`

**Comment by abrevers-nttdata** [comment]
Also:
`-H, --hostname <hostname>` seems to be wrong.

`-H, --host <hostname>` seems to be correct.

(Actually it’s the *script* that should honor the "--hostname" option, as it’s both aligned with the "--username" option, and also more precise).

**Comment by ascii42** [comment]
should be fixed with version 0.1.1

**Comment by abrevers-nttdata** [comment]
Also, some long options are documented but do not work:
- `--warning-cs-current-session`
- `--critical-cs-current-session`

The short option equivalents work, though, but long options are better anyway (https://superuser.com/a/174568/919822). :-)
