### ISSUE TITLE
 Unknown parameter: Problem while gathering API Token

### ISSUE THREAD

**Issue by jbaumgar1** [ascii42/check_vmware_horizon#2]
Hi,

I've got this message when I try to use the following command.

./check_vmware_horizon.sh -D domain.com -H horizon.domain.com -P password -U username

Do you have any idea on what is missing? I'm running Horizon server 2309.

Best

**Comment by ascii42** [comment]
Hi,

The Parameters should be ok, maybe you could try -d for debug mode.
I guess there is something wrong with the user. i.e. username or bad password or permissons....

In that case the debug mode should print something like + [[ {"status":"UNAUTHORIZED","timestamp":1703241420944,"errors":[{"error_key":"auth.token.invalid.error","

**Comment by jbaumgar1** [comment]
I've put -d at the end but still have the same output.

Unknown parameter: Problem while gathering API Token
Usage: check_vmware_horizon.sh [-h] [-V] -H <hostname> [-U <username>] [-P <password>] [-D <domain>] [-opts] [-w <warning>] [-c <critical>] [-v]

**Comment by jbaumgar1** [comment]
Ok my bad, I was using another DNS entry to point to the VIP which doesn't work probably due to the fact that it's not the same domain
